stages:
  ingest:
    cmd: conda run -n FinQA_v4 python -m src.components.data_ingestion
    outs:
      - data/raw/agnews.csv

  train:
    cmd: conda run -n FinQA_v4 python -m src.pipeline.training_pipeline
    deps:
      - data/raw/agnews.csv
      - src/
    outs:
      - models/
      - artifacts/
   