name: MLOps CI/CD Pipeline

on:
push:
branches:
- main

jobs:
build-and-deploy:
runs-on: ubuntu-latest

steps:
  - name: Checkout Repo
    uses: actions/checkout@v4

  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  - name: Build and Push Docker Image
    run: |
      docker build -t santypol/mlops-agnews:latest .
      docker tag santypol/mlops-agnews:latest santypol/mlops-agnews:${{ github.sha }}
      docker push santypol/mlops-agnews:latest
      docker push santypol/mlops-agnews:${{ github.sha }}

  - name: Deploy to EC2 via SSH
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        echo "🚀 Deploying on EC2..."

        if [ ! -d "MLOPS_DEMO" ]; then
          git clone https://github.com/SANTYPOL/MLOPs-AGNEWS.git MLOPS_DEMO
        fi

        cd MLOPS_DEMO
        git pull origin main

        echo "🐳 Restarting container..."
        sudo docker pull santypol/mlops-agnews:latest
        sudo docker stop mlops-api || true
        sudo docker rm mlops-api || true
        sudo docker run -d -p 8000:8000 --name mlops-api santypol/mlops-agnews:latest

        echo "✅ Deployment complete!"