name: MLOps CI/CD Pipeline

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest


steps:
  - name: Checkout Repo
    uses: actions/checkout@v4

  - name: Deploy to EC2 via SSH
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        echo "🚀 Connecting to EC2..."

        if [ ! -d "MLOPS_DEMO" ]; then
          git clone https://github.com/SANTYPOL/MLOPs-AGNEWS.git MLOPS_DEMO
        fi

        cd MLOPS_DEMO
        git pull origin main

        echo "📦 Running pipeline..."
        pip install -r requirements.txt
        dvc repro --force

        echo "🐳 Restarting Docker..."
        sudo docker pull santypol/mlops-agnews:v2
        sudo docker stop mlops-api || true
        sudo docker rm mlops-api || true
        sudo docker run -d -p 8000:8000 --name mlops-api santypol/mlops-agnews:v2

        echo "✅ Deployment complete!"
```
